version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - URL=http://horizon:8000
    depends_on:
      - stellar_horizon
    restart: always

  stellar_horizon:
    image: stellar/quickstart:testing
    command: ["--testnet", "--enable-soroban-rpc"]
    ports:
      - "8000:8000"
    restart: always
